# Generated by Django 5.0.4 on 2024-04-06 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(choices=[('user', 'normal user'), ('expert', 'domain expert')], max_length=50)),
                ('profession', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('username', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
