# Generated by Django 5.0.4 on 2024-04-06 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_role_expert_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert_request',
            name='username',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='core.user', to_field='display_name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='username',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='core.user', to_field='display_name'),
        ),
    ]
