# Generated by Django 5.0.4 on 2024-04-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factcheck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factresmodel',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='factresmodel',
            name='noSentimentRes',
            field=models.IntegerField(default=0),
        ),
    ]
