# Generated by Django 5.0.4 on 2024-04-06 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factcheck', '0003_verdictres_voteres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verdictres',
            name='postresID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factcheck.factreqmodel'),
        ),
    ]
